parameters:
#    it_viet_site.example.class: ITViet\SiteBundle\Example

services:
    it_viet_site.extension:
        class: ITViet\SiteBundle\Extension\SiteExtension
        tags:
          - { name: twig.extension }
        arguments: [@service_container]

    member_authentication_hander:
        class: ITViet\SiteBundle\Handler\MemberAuthenticationHandler
        arguments: [@router, @translator]

    it_viet_site.url_slugger:
        class: ITViet\SiteBundle\Model\UrlSlugger
        arguments: [@it_viet_site.char_converter]

    it_viet_site.char_converter:
        class: ITViet\SiteBundle\Model\CharConverter

    it_viet_site.member_service:
        class: ITViet\SiteBundle\Service\MemberService
        #arguments: [@doctrine.orm.default_entity_manager, @doctrine.orm.logger_entity_manager, @security.context]
